### ISSUE TITLE
where are the .map.gz found?

### ISSUE THREAD

**Issue by Erwyn** [yast/yast-country#167]
Hello there, I'd like to make a pull request to add the french dvorak (bépo) to the supported keyboard layouts.

I'm very new to this, and a question I have is regarding this entry:
https://github.com/yast/yast-country/blob/master/keyboard/src/data/keyboard_raw.ycp#L107

Where are those `.map.gz` files located and where to find the right ones to add to the new entry?

**Comment by jyeray** [comment]
I think they are located here ```/usr/share/kbd/keymaps/``` .

Maybe [this](https://wiki.archlinux.org/index.php/Keyboard_configuration_in_console) and [this](https://wiki.archlinux.org/index.php/Keyboard_configuration_in_Xorg) can be helpful for you.

**Comment by ancorgs** [comment]
Yes, they live in `/usr/share/kbd/keymaps/` and are provided by the `kbd` package.
